### PR TITLE
Issue 12

### LINKED ISSUE #12: Change Titlebar Logo to something more fitting
The titlebar logo can be changed as the logo does not resemble what the website aims to achieve

WhatsApp Image 2022-11-19 at 21 45 09

### PR DESCRIPTION
**Pull request by jcachinho**
Here's my pull request for issue 12: Change Titlebar Logo to something more fitting

I added the logo.png (stored on src/assets/logo.png) to manifest.json and in the rel link inserted the logo.png.

### CODE REVIEW

**Review by Takashi069 — CHANGES_REQUESTED** [review]
Unfortunately, the title bar is still showing the react icon in the development server.

I looked into the issue and I think it is because the image was not present in the public folder.  My bad :sweat_smile:

So put the logo in the public folder and in the **manifest.json**,  change it from
```json
{
      "src": "src/assets/logo.png",
      "type": "image/png",
      "sizes": "512x512"
}
``` 
to 
```json
{
      "src": "logo.png",
      "type": "image/png",
      "sizes": "512x512"
}
```
I think it should be working after this change.

**Comment by jcachinho** [comment]
Change request done in my last commit: 039f784cc7cca3d94e807aca928a8b3a732ea917

Check in your side to see if it's okay.

Thanks.

**Review by Takashi069 — APPROVED** [review]

**Comment by Takashi069** [comment]
Awesome work @jcachinho 

Thanks for your help !!! :+1:

**Review by Takashi069 — CHANGES_REQUESTED** [review]
**Do a pull from the master branch of the original repo**

I think your branch is behind ours by a few commits. The latest changes in our branch is not being reflected in the review preview by Netlify.

**Review by Takashi069 — CHANGES_REQUESTED** [review]
Do a pull from the master branch of the original repo

**Comment by jcachinho** [comment]
@Takashi069 done.

Can you check if it is okay ?

Thanks.

**Review by Takashi069 — APPROVED** [review]

**Comment by Takashi069** [comment]
@jcachinho 

Yep, it's all good :+1: 
Thanks for the help and contribution :smile:

**Pull request merged**
